### ISSUE TITLE
vROPs v.8.0.1 compatibility

### ISSUE THREAD

**Issue by razvani** [johnddias/vrops-super-metric-numa-optimize#1]
Hi John,

Thank you for your great work to create NUMA supermetrics for vROPS 7.5.
I used them and are really great. Unfortunately, after migration to vROPs v.8.0.1 the supermetrics are not working anymore.

Can you help me, please, to find out what could be the cause?

Thank you in advance!

**Comment by johnddias** [comment]
Sure I will take a look.

**Comment by johnddias** [comment]
OK, there is a bug in 8.0.1 and 8.1 which impacts the Super Metric preview.  This is why you are not seeing this in preview but the Super Metric does work once you assign to a policy and a collection cycle occurs.

**Comment by razvani** [comment]
Hi John,
Thank you for your prompt answer. Indeed this was the issue.
Have a nice weekend!
